### ISSUE TITLE
accepting invites does not work

### ISSUE THREAD

**Issue by w-o-a-h** [BtoBastian/Javacord#103]
doing acceptInvite does not join the guild all it does is print this in console
```
[pool-61-thread-2] DEBUG d.btobastian.javacord.ImplDiscordAPI - Trying to accept invite (code: [REMOVED])
[pool-61-thread-2] INFO  d.btobastian.javacord.ImplDiscordAPI - Accepted invite and waiting for listener to be called (code: [REMOVED], server id: [REMOVED])
```

**Comment by BtoBastian** [comment]
Are you using a user account or a bot account? Only "real" users can accept invites.

**Comment by w-o-a-h** [comment]
user account it also seems that i cant reply to messages too is this because i have more then 1 account running on the same jvm?

**Comment by BtoBastian** [comment]
Can you please add a `.get()` after the reply() method and check which exception it throws?
Something like this:
```java
try {
  msg.reply("Test").get();
} catch (Exception e) {
  e.printStackTrace();
}
```

**Comment by w-o-a-h** [comment]
nevermind sending messages does work

**Comment by w-o-a-h** [comment]
yeah acceptInvite does not work

**Comment by w-o-a-h** [comment]
```java
try {
                                a.acceptInvite("[REMOVED]", new FutureCallback<Server>() { //https://discord.gg/[REMOVED]
                                    @Override
                                    public void onSuccess(Server server) {
                                        System.out.println(server.getName());
                                    }

                                    @Override
                                    public void onFailure(Throwable t) {
                                        t.printStackTrace();
                                    }
                                }).get();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
```

**Comment by BtoBastian** [comment]
Is there any response or a neither `onSucess`, nor `onFailure` called?

**Comment by cbwolfe32** [comment]
I've also had this issue. The `onSuccess `is called but the account doesn't join the server. The user isn't in any other servers so it's not a 100 server limit.

**Comment by w-o-a-h** [comment]
the onSucess nor the onFailure is being called for me.

**Comment by justincenteno99** [comment]
This still doesn't work by the way, I called the future with the callback and it shows this:
`[pool-39-thread-2] INFO de.btobastian.javacord.ImplDiscordAPI - Accepted invite and waiting for listener to be called (code: *******, server id: REMOVED)`

Code is:
`api.acceptInvite("*******", new FutureCallback<Server>() {
                                @Override
                                public void onSuccess(@Nullable Server server) {
                                    if (server != null) {
                                        System.out.println("Joined discord server with " + (server.getMemberCount() - 1) + " members!");
                                    }
                                }

                                @Override
                                public void onFailure(Throwable throwable) {
                                    System.out.println(throwable.getMessage());
                                }
                            });`

**Comment by w-o-a-h** [comment]
yeah it still is doing it.

**Comment by BtoBastian** [comment]
I just did some testing and it seems like Discord changed how invites are accepted by clients.
Client accounts are not offically recommended by Discord (in fact they are not allowed at all) and I guess they intentionally changed this as automatic accepting of invites can easily be abused for spam bots etc.
So I'm not sure if I should really update to the new behaviour (which would also need some reverse engineering as there's no documentation about the client api) or just remove this functionality.

**Comment by w-o-a-h** [comment]
https://discordapp.com/api/v6/invite/{CODE}

Set "authorization" in the header to the token and send it as a post request.

Response:
{"inviter": {"username": "{REMOVED}", "discriminator": "{REMOVED}", "id": "{REMOVED}", "avatar": "{REMOVED}"}, "code": "{REMOVED}", "guild": {"verification_level": 0, "features": [], "name": "{REMOVED}", "splash": null, "id": "{REMOVED}", "icon": "{REMOVED}"}, "channel": {"type": 0, "id": "{REMOVED}", "name": "{REMOVED}"}}

And it worked.

**Comment by justincenteno99** [comment]
Ah makes sense, thanks @w-o-a-h
