### ISSUE TITLE
[Need help] updateRole()  incomprehension

### ISSUE THREAD

**Issue by ungarscool1** [BtoBastian/Javacord#107]
Hello,
I don't understand this function at updateRole(User user, Role Role[])
What is Role Role[] ?
My code `server.updateRoles(message.getAuthor(), role.equals("Custom"));`
Thanks to help me

**Comment by MythTheWolf** [comment]
Role[] is an array of Roles. This allows you to set multiple roles to a user

**Comment by ungarscool1** [comment]
Okay, but my code is incorrect when i apply that
`@SuppressWarnings({ "unchecked", "rawtypes" })
					ArrayList<Role> role = new ArrayList();
					role.add(Role[]);
					message.delete();
					message.reply("GG à toi "+message.getAuthor().getMentionTag()+", tu as trouvé la phrase magique...");
					server.updateRoles(message.getAuthor(), role[6]);`
It's correct ?

**Comment by MythTheWolf** [comment]
No,that is not correct. When you supply a index to a array, [int], it represents the element of that position. You are trying to put a role object instead of the entire array. The correct way is `updateRoles(author,role)`

**Comment by MythTheWolf** [comment]
EDIT: Turn the list to an array first

**Comment by ungarscool1** [comment]
So, 
```
ArrayList<Role> role = new ArrayList();
role.add(6);
server.updateRoles(message.getAuthor(), role[]);
```
Or 
```
ArrayList<Role> role = new ArrayList();
role.add(Role[6]);
server.updateRoles(message.getAuthor(), role[]);
```
It's correct? I think not...

**Comment by MythTheWolf** [comment]
No,you need to convert the ArrayList to an array. This is simple java

**Comment by ungarscool1** [comment]
Oh, okay thanks you
