### ISSUE TITLE
Major - Maven Info incorrect.

### ISSUE THREAD

**Issue by thatsimplekid** [BtoBastian/Javacord#108]
http://repo.javacord.org/ is not an active domain. DNS lookups fail.
This bug causes the library to be unusable, as it can only be downloaded from your repo.

**Comment by GamingAndStuffs** [comment]
As the main readme says, that is placeholder information, and the real information is dynamically updated on the Javacord Discord Server: https://discord.gg/0qJ2jjyneLEgG7y3

**Comment by thatsimplekid** [comment]
After doubting myself, I have checked both the v3 and master branch, and neither versions of the README state that it is placeholder info.

**Comment by GamingAndStuffs** [comment]
Oh, sorry, my memory was incorrect about the readmes saying it, but it is placeholder information.

**Comment by BtoBastian** [comment]
@GamingAndStuffs is right, it was only meant as a placeholder. However, I updated the README to the correct information.
