### ISSUE TITLE
Joining the Voice Chat

### ISSUE THREAD

**Issue by wherkamp** [BtoBastian/Javacord#109]
Am I able to make my bot join the voice chat and play "music" or sounds?

**Comment by BoneyIsSpooky** [comment]
No.

**Comment by wherkamp** [comment]
Thank you, That would be a cool feature. again Thank you.

**Comment by Vampire** [comment]
That is on the todo list for the v3 rewrite. Until then you would have to use D4J or JDA if you really want the feature.

**Comment by wherkamp** [comment]
Ok thank you.

**Comment by BoneyIsSpooky** [comment]
Vote to close as this question has been fully answered.
