### ISSUE TITLE
Implementation of discovering Listeners

### ISSUE THREAD

**Issue by MysticalHerobine** [BtoBastian/Javacord#14]
Extending your listeners (e.g. MessageCreateListener) into another interface causes errors where the default java lookup of interfaces isn't enough. I recommend using Apache Common Lang's ClassUtils.getAllInterfaces(Class<?>) which allows for lookup of ALL interfaces, not just the ones declared in the class.

I've implemented a hackish version using Java Reflection on your ImplDiscordAPI and Javacord classes. This was my method:

        @Override
	public void registerListener(Listener listener)
	{
		for (Class<?> implementedInterface : ClassUtils.getAllInterfaces(listener.getClass()))
		{
			if (Listener.class.isAssignableFrom(implementedInterface))
			{
				List<Listener> listenersList = listeners.get(implementedInterface);
				if (listenersList == null)
				{
					listenersList = new ArrayList<>();
					listeners.put(implementedInterface, listenersList);
				}
				synchronized (listenersList)
				{
					listenersList.add(listener);
				}
			}
		}
	}

I hope this is solved as it is a very useful when making custom classes to house command information that every command shall use.

Thanks in advance for consideration,
        ~Mystic

**Comment by BtoBastian** [comment]
Hey, 
thank you.
I'll fix it when I'm back from vacation.

**Comment by BtoBastian** [comment]
Fixed in dev branch.
I'll update the master branch, soon™.
https://github.com/BtoBastian/Javacord/commit/b8def2cd93efe117ee048a9e9ae990dd4a9f9093
