### ISSUE TITLE
'Timestamp' attribute on messages ignores the timezone.

### ISSUE THREAD

**Issue by me4502** [BtoBastian/Javacord#16]
Currently the timestamp attribute on messages completely ignores the timezone, which causes major issues when comparing the time. As no TZ is supplied, Java assumes it wants to use the system time, which means unless the system is set to use UTC, the time will be wrong.

This can be remedied in one of two ways:
* Just set the calendar instance to UTC
* Or better, implement proper timestamp handling that includes the timezone.

**Comment by BtoBastian** [comment]
https://github.com/BtoBastian/Javacord/commit/a472914c847a45dcc40b268a763fcd1322f6ad09
Thank you very much!
