### ISSUE TITLE
Request for updating latest version

### ISSUE THREAD

**Issue by pupnewfster** [BtoBastian/Javacord#198]
I have been developing a bot using Javacord 2.0.17. I do understand that it is not recommended to start developing a new bot with Javacord 2.x.x, but it is one of the easier libraries to use that I have found. I have been trying to make it so that I can change what category a channel is in after I create it. I looked through the commits for the 2.x.x branch and I see that you have already added parent id support. If it would not be too much trouble would you mind creating a final 2.0.18 version with all the changes in the branch that have happened since the 2.0.17 version was released?

**Comment by Vampire** [comment]
Are you aware that you should not use v2, because you should use v3 instead? If you think v2 is the easiest to use, you will find v3 be usable by babies tust never had a keyboard in their hands. ;-)

**Comment by pupnewfster** [comment]
I can see where I was unclear, I had originally meant that javacord is easiest compared to other libraries I have tried in the past. I do not doubt that v3 is probably easier to use than v2; however, I decided to use v2 as v3 is not feature complete.

Looking at the code, v3 does not have a way to set the parent id of voice channels, so switching from v2 to v3 would not help me in this situation. The main reason I opened this issue is that the code is already there for setting parent channels, it just has not been put into a maven repo.

**Comment by Vampire** [comment]
v3 is nearer to feature completeness than v2 is and actually will very soon replace v2 as the officially latest release. 

And I don't know what code you are looking at, the one I look at have that possibility. Maybe you looked at `VoiceChannel` instead of  `ServerVoiceChannel`?

Private channels and group DM channels are also voice channels, yet it doesn't make any sense to set their category.

**Comment by pupnewfster** [comment]
I may try switching to v3 if it is nearer to feature completness than v2. Searching the files I was looking at `ImplServerVoiceChannel` in v3 as both `VoiceChannel` and `ServerVoiceChannel` did not have a method for setting parent but I had seen a reference to getting the parent. Upon closer inspection I see that there is a setCategory method so I will try that, and afterwards close this issue.

**Comment by Vampire** [comment]
Yes, `setCategory` is exactly what you are after I think. :-)

**Comment by pupnewfster** [comment]
I managed to get it working using v3 and setCategory. Thank you for your help.
