### ISSUE TITLE
Can't login to 'real' account

### ISSUE THREAD

**Issue by TheUltimatePleb** [BtoBastian/Javacord#22]
I'm attempting to log into a real account using the API. But it's throwing an error and an exception saying this:

> java.lang.IllegalArgumentException: 400 Bad request! Maybe wrong email or password?
> 	at de.btobastian.javacord.ImplDiscordAPI.requestTokenBlocking(ImplDiscordAPI.java:1014)
> 	at de.btobastian.javacord.ImplDiscordAPI.connectBlocking(ImplDiscordAPI.java:160)
> 	at de.btobastian.javacord.ImplDiscordAPI$2.call(ImplDiscordAPI.java:147)
> 	at de.btobastian.javacord.ImplDiscordAPI$2.call(ImplDiscordAPI.java:144)

I made sure the email and password are right. I even went to the discord program, logged out. Copied the email I put. Put it in the email box, copied the password from the program and hit login on discord, and it logged me in. So I do not know what the problem is :/ . I Do not have 2-FA enabled. I only require an email and password to login.

**Comment by TheUltimatePleb** [comment]
I was able to log in using my own code. Which sadly means I will need to edit the source :P . If other people are having this issue as well, and it isn't just me, I may make a pull request.

**Comment by TheUltimatePleb** [comment]
Please See the latest pull request for a fix(I didn't do the pull request :P)

**Comment by BtoBastian** [comment]
#23 fixed it.
Thank you.
