### ISSUE TITLE
User Roles don't refresh

### ISSUE THREAD

**Issue by modsfabio** [BtoBastian/Javacord#246]
Hello, I'm using javacord-2.0.17-shaded.jar

I'm getting user roles with this code:
`user.getRoles(this.api.getServerById(this.serverID))`

It works fine for the first few hours and returns the User's roles.
But it stops working after a random time and doesn't refresh the roles.

For example if I remove a role from a User in Discord `user.getRoles` still returns the removed Role.

Am I doing anything wrong? Is there a cache or something?

**Comment by BtoBastian** [comment]
Solved on the Discord server
