### ISSUE TITLE
Cannot login with a username and password

### ISSUE THREAD

**Issue by rskupnik** [BtoBastian/Javacord#25]
Trying to use the API and connect with a username and password is impossible. Tracing the bug - it seems that the JSON payload of the response contains an "[username] field is required" and similar for password - it seems your login request is invalid somehow.

**Comment by MinnDevelopment** [comment]
This was fixed in fef7d09 iirc.

**Comment by BtoBastian** [comment]
MinnDevelopment is right.
It's already fixed in the dev branch.
