### ISSUE TITLE
Cant use javacordhandler and commandhandler

### ISSUE THREAD

**Issue by christoffer15** [BtoBastian/Javacord#252]
JavacordHandler
(de.btobastian.javacord.DiscordApi)
in JavacordHandler cannot be applied
to
(de.btobastian.javacord.DiscordAPI)

**Comment by BoneyIsSpooky** [comment]
You are using an old version of Javacord

**Comment by christoffer15** [comment]
wjht is the newest?

**Comment by BoneyIsSpooky** [comment]
Version 3, which is in development. On github, switch to the branch `v_3`. Use commit `6a60432` of Javacord for compatibility with the latest sdcf4j

**Comment by christoffer15** [comment]
Still the same error on the newest version. but now its (org.javacord.DiscordApi insted of de.btobastian.javacord.Discordapi
)

**Comment by BoneyIsSpooky** [comment]
You did not follow my instructions. Refer to the commit id I gave you.

**Comment by christoffer15** [comment]
i am this is my pom.xml file 
[xml version=1.0 encoding=UTF-8.txt](https://github.com/BtoBastian/Javacord/files/1844858/xml.version.1.0.encoding.UTF-8.txt)

**Comment by BoneyIsSpooky** [comment]
I don't know what that is but it is not a POM nor is it an xml file. Try again.

**Comment by christoffer15** [comment]
Here is the xml file
```xml
<?xml version="1.0" encoding="UTF-8"?>

-<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0">

<modelVersion>4.0.0</modelVersion>

<groupId>com.chrisune</groupId>

<artifactId>discordbot</artifactId>

<version>1.0-SNAPSHOT</version>


-<build>


-<plugins>


-<plugin>

<groupId>org.apache.maven.plugins</groupId>

<artifactId>maven-compiler-plugin</artifactId>


-<configuration>

<source>1.8</source>

<target>1.8</target>

</configuration>

</plugin>

</plugins>

</build>


-<repositories>


-<repository>

<id>jitpack.io</id>

<url>https://jitpack.io</url>

</repository>

</repositories>


-<dependencies>


-<dependency>

<groupId>de.btobastian.sdcf4j</groupId>

<artifactId>sdcf4j-core</artifactId>

<version>v1.0.9</version>

</dependency>

<!-- The module for your preferred lib -->



-<dependency>

<groupId>de.btobastian.sdcf4j</groupId>

<!-- Possible artifact ids: sdcf4j-javacord, sdcf4j-jda3, sdcf4j-discord4j -->


<artifactId>sdcf4j-javacord</artifactId>

<version>v1.0.9</version>

</dependency>


-<dependency>

<groupId>de.btobastian</groupId>

<artifactId>Javacord</artifactId>

<!-- See below what to insert here -->


<version>6a60432</version>

</dependency>

<!-- A SLF4J comaptible logging framework. I would recommend to use logback -->



-<dependency>

<groupId>ch.qos.logback</groupId>

<artifactId>logback-classic</artifactId>

<version>1.2.3</version>

</dependency>

</dependencies>

</project>
```

**Comment by christoffer15** [comment]
error it cant find import de.btobastian.javacord.DiscordApi; and i can only find org.javacord.DiscordApi

**Comment by BtoBastian** [comment]
Javacord version: `e078151af2`
sdcf4j version: `350ba0448c`

These two versions should be compatible. Please join our Discord server ([Invite](https://discord.gg/0qJ2jjyneLEgG7y3)) for further questions: Issues are only meant for bug reports and feature suggestions.
