### ISSUE TITLE
Login With 2FA Enabled

### ISSUE THREAD

**Issue by gudenau** [BtoBastian/Javacord#29]
I enabled two factor authentication on my account, because of this I can not log in with this library. I would like it it you could allow the use of two factor authentication.

**Comment by BtoBastian** [comment]
Hello,

I would recommend you to use a bot account instead of a "real" user account.
Nevertheless you can still log in to an user account with 2FA enabled by using a token instead of Email & Password.

**Comment by BtoBastian** [comment]
Hello,

could you solve the problem?

**Comment by gudenau** [comment]
The token worked, but that's not a real fix.

**Comment by BtoBastian** [comment]
It's not recommended to use username + password everytime.
Logging in with tokens is the recommended method (for both bot and user accounts) even the browser or the desktop app cache the token.
2FA won't be supported by Javacord.
