### ISSUE TITLE
Is there an option for clear/prune all messages in a server?

### ISSUE THREAD

**Issue by sh4dxw** [BtoBastian/Javacord#30]
I have been looking for this for about 2 days now, i am using Javacord too, i might be missing it out, but could someone tell me if it's possible with Javacord?

Thanks.

**Comment by hvze** [comment]
See if there is a way to get all messages sent to a server, then just loop through those and delete.

**Comment by BtoBastian** [comment]
Looping through all messages and deleting them is possible but not recommended by Discord.
Discord provides an endpoint to delete all messages in a channel and I'll try to add support for it asap.

**Comment by VenHayz** [comment]
@BtoBastian that'd be great. I'm having the same troubles today, making my first Discord bot. Thanks for making the API so easy, too.

**Comment by BtoBastian** [comment]
Hey,

sadly I was wrong. There is no way to delete all message in a channel.
However, I added Channel#bulkDelete() which takes an array of messages which should be deleted as a parameter. If you plan on deleting a lot of messages at once you should use this method.
https://github.com/BtoBastian/Javacord/commit/8598febf478e6787470c0ea41196ac97bcda7417
