### ISSUE TITLE
[Request] Add support for Nicknames

### ISSUE THREAD

**Issue by Mohron** [BtoBastian/Javacord#32]
Hi, I can't find any way to utilize nicknames using Javacord. Either I just need sent in the right direction or there currently isn't support for nicknames. If it's the later I would like to request support be added.

**Comment by BtoBastian** [comment]
Hey,

nicknames are on my TODO list and I'm going to add them, soon.

**Comment by BtoBastian** [comment]
Hey,

nicknames are now supprted in the dev branch (https://github.com/BtoBastian/Javacord/commit/6120ee92a4d1a99297e036ace895c857a2e8a1e0) and will be included in the next version (2.0.14).
