### ISSUE TITLE
Unfinished Permission List

### ISSUE THREAD

**Issue by MysticalHerobine** [BtoBastian/Javacord#35]
The permission list isn't completed yet, but here is the fix for the list for you:

> // general
> 	CREATE_INSTANT_INVITE(0),
> 	KICK_MEMBERS(1),
> 	BAN_MEMBERS(2),
> 	ADMINISTATOR(3),
> 	MANAGE_CHANNELS(4),
> 	MANAGE_SERVER(5),
> 	ADD_REACTIONS(6),
> 
> 	// chat
> 	READ_MESSAGES(10),
> 	SEND_MESSAGES(11),
> 	SEND_TTS_MESSAGES(12),
> 	MANAGE_MESSAGES(13),
> 	EMBED_LINKS(14),
> 	ATTACH_FILE(15),
> 	READ_MESSAGE_HISTORY(16),
> 	MENTION_EVERYONE(17),
> 	USE_EXTERNAL_EMOJIS(18),
> 
> 	// voice
> 	VOICE_CONNECT(20),
> 	VOICE_SPEAK(21),
> 	VOICE_MUTE_MEMBERS(22),
> 	VOICE_DEAFEN_MEMBERS(23),
> 	VOICE_MOVE_MEMBERS(24),
> 	VOICE_USE_VAD(25),
> 	
> 	// misc
> 	CHANGE_NICKNAME(26),
> 	MANAGE_NICKNAMES(27),
> 	MANAGE_ROLES(28),
> 	MANAGE_WEBHOOKS(29),
> 	MANAGE_EMOJIS(30);

Those are the enums for the PermissionType class, hope that helps :P

**Comment by BtoBastian** [comment]
Thank you very much :)

**Comment by Almighty-Alpaca** [comment]
JDA's list is complete in case you want to use that for reference https://github.com/DV8FromTheWorld/JDA/blob/master/src/main/java/net/dv8tion/jda/core/Permission.java

**Comment by BtoBastian** [comment]
There's also the official list from Discord. But thank you, I'll complete the permissions tomorrow :)
https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/topics/Permissions.md

**Comment by MysticalHerobine** [comment]
That's the exact list I used to create it :)
