### ISSUE TITLE
java.lang.IllegalStateException when connecting

### ISSUE THREAD

**Issue by pcr3w** [BtoBastian/Javacord#42]
Roughly 2/3rds of the times that I attempt to connect to my bot, I get the following error:

```
java.lang.IllegalStateException: Socket closed before ready packet was received!
	at de.btobastian.javacord.ImplDiscordAPI.connectBlocking(ImplDiscordAPI.java:162)
	at de.btobastian.javacord.ImplDiscordAPI$2.call(ImplDiscordAPI.java:144)
	at de.btobastian.javacord.ImplDiscordAPI$2.call(ImplDiscordAPI.java:141)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by BtoBastian** [comment]
Hey,
Can you please enable the debug mode and see if there is any additional information?

**Comment by pcr3w** [comment]
There's no other information with debug mode on (I'm assuming that you mean the logger debug mode).

**Comment by BtoBastian** [comment]
Hey,
```java
api.setWaitForServersOnStartup(false);
```
works as a temporary fix. I still have to find out the reason for this error, but this is at least a temporary solution for everyone with this problem (It seems to not affect everyone).

**Comment by pcr3w** [comment]
That seems to be working for the moment - thanks.

**Comment by iiiLollo** [comment]
I noticed the following, I get this error when I try to connect to a server after my connection didn't close property. This can happen if the application running the api crashes before running the api.disconnect() command.

But I also noticed that api.disconnect() sometimes doesn't close the connection properly,
I found the following lines in the log after running api.disconnect(), it looks like it's trying to connect again. 

d.b.j.utils.DiscordWebsocketAdapter - Websocket closed with reason null and code 1000 by client!
d.b.j.utils.DiscordWebsocketAdapter - Sending resume packet
d.b.j.utils.DiscordWebsocketAdapter - Received HELLO packet
d.b.j.utils.DiscordWebsocketAdapter - Could not resume session. Reconnecting now...
d.b.j.utils.DiscordWebsocketAdapter - Sending identify packet

**Comment by Yorkforce** [comment]
@BtoBastian Has there been any update on this at all? We have always had this problem every couple of weeks or so, but we have always been able to use the discord reconnect command a few times to eventually get it to connect, however right now ti will not connect at all, i just tried running the discord reconnect command over 50 times on one of our servers and it just won't have it.

**Comment by BtoBastian** [comment]
Hey,
if you have debugging enabled, what is the full log?
Is there a `Received READY packet` before receiving the error?
Is there a `Websocket closed ...` message?

**Comment by Yorkforce** [comment]
Its the same message that pcr3w posted.
java.lang.IllegalStateException: Socket closed before ready packet was received!

This morning it seems better, I just checked and only 2 servers hadn't automatically reconnected (they auto restart every 8 hours) and running the discord reconnect commands on those 2 servers both reconnected straight away but the problem will eventually return again and there will be periods of time where we are unable to connect at all, as was the case last night.

**Comment by BtoBastian** [comment]
And afterwards the `Socket closed before ready packet was received` message?

**Comment by Yorkforce** [comment]
Yep directly afterwards:
https://pastebin.com/AT28YtQx

**Comment by BtoBastian** [comment]
Are there still people experiencing this bug?

**Comment by iObsidian** [comment]
Hello Bastian, I've encountered this bug. I'll keep you updated if updating to the latest Javacord version fixes it!
