### ISSUE TITLE
[REQUEST] Creation & Join Dates

### ISSUE THREAD

**Issue by raxixor** [BtoBastian/Javacord#43]
Hi, it's me again.

I found something that I needed, yet couldn't find in Javacord.
Creation dates for Servers & Users,
Join dates for Users.

**Comment by BtoBastian** [comment]
Hey,

Creation dates for Servers and Users do not exist in the discord api, but I can add user join dates.
You can use the join date of the server owner for the server creation time (which can be wrong if the ownership was transfered).

**Comment by GrandPanda** [comment]
You can derive the creation date of any object from its snowflake.

**Comment by BtoBastian** [comment]
Ohh, right. Totally forgot about that.

**Comment by BtoBastian** [comment]
Will be part of the next version. :)
See https://github.com/BtoBastian/Javacord/commit/404b5e485edba077ef05fa0ffa3884de64691cfb
