### ISSUE TITLE
I'm sorry but I must be really stupid. 

### ISSUE THREAD

**Issue by RegisDeVallis** [BtoBastian/Javacord#48]
How do I send a message? I'm not talking about replying to one I'm talking about sending a message in general. I've looked through the source files and the javadocs and I cant find anything. 

Thanks

**Comment by shawishi** [comment]
For such questions, it's better to ask in Javacord's Discord #support channel. https://discord.gg/0qJ2jjyneLEgG7y3

**Comment by RegisDeVallis** [comment]
Thanks, didn't know about that
