### ISSUE TITLE
Clear chat

### ISSUE THREAD

**Issue by SunnyElite** [BtoBastian/Javacord#54]
Hi, I want to clean up the chat.
But when my code is executed, nothing happens.
Can you please tell me how to do this?
My code: 
`Future<MessageHistory> xuy = channel.getMessageHistory(2);
channel.bulkDelete(String.valueOf(xuy));`

**Comment by shawishi** [comment]
`channel.bulkDelete(xuy.getMessages().toArray(new Message[] {}));` should do the trick

**Comment by SunnyElite** [comment]
Thanks 👍 :)
