### ISSUE TITLE
not work with multiple bot / NullPointerException

### ISSUE THREAD

**Issue by poop-code** [BtoBastian/Javacord#59]
if define multiple bot
Can't send msg to channels.

api.getChannelById(channelID).sendMessage(RESTART_MSG);

api is NOT NULL
channelID is NOT NULL
RESTART_MSG is NOT NULL

api.getChannelById(channelID) is NULL

api.getChannels().isEmpty() is TRUE

 com.google.common.util.concurrent.AbstractFuture executeListener
Fatal: RuntimeException while executing runnable com.google.common.util.concurrent.Futures$4@6f4e08e0 with executor MoreExecutors.directExecutor()
java.lang.NullPointerException
	at org.*crawler.bot.DiscordBot$1.onSuccess(DiscordBot.java:67)
	at org.*.crawler.bot.DiscordBot$1.onSuccess(DiscordBot.java:1)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1132)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:435)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:900)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:811)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:653)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by BtoBastian** [comment]
Hey, can you please show some of your code?

**Comment by poop-code** [comment]
https://github.com/poop-code/PokemonGo-Web-Crawler/blob/master/src/main/java/org/jh/pogo/crawler/bot/DiscordBot.java

if define multiple bot not work like
DiscrodBot bot1,bot2

**Comment by Treescrub** [comment]
The bot is in the server you are trying to send the message to, right?

**Comment by poop-code** [comment]
Yes. send to message to Channel
only 1 bot works.
if define 2, or more then null pointexception come out

**Comment by Treescrub** [comment]
If you do: 
`DiscordBot bot1,bot2;`
It will of course throw a NullPointerException if you try to call connect() because it will not have been constructed

**Comment by poop-code** [comment]
What the... 
wait i will give you code OK? 
I'm not stupid like that code

**Comment by poop-code** [comment]
`package testjavacord;

import java.io.File;

import com.google.common.util.concurrent.FutureCallback;

import de.btobastian.javacord.DiscordAPI;
import de.btobastian.javacord.Javacord;

public class DiscordTester {
	
	private final static String TOKEN = "tokenval";
	private final static String TOKEN2 = "tokenval2";
	private final static String channelID4TOKEN = "336438218490000000";
	private final static String channelID4TOKEN2 = "3364383390000000000";
	

	public static void main(String[] args) {
		SampleDiscordBot bot1,bot2;
		bot1 = new SampleDiscordBot(TOKEN,channelID4TOKEN);
		bot2 = new SampleDiscordBot(TOKEN2,channelID4TOKEN2);
		bot1.connect();
		bot2.connect();

	}

}

class SampleDiscordBot {
	private String 		token;
	private String 	channel;
	
	private DiscordAPI 	api;
	
	
	public SampleDiscordBot(String token,String channel) {
		this.token = token;
		this.channel = channel;
		
	}//end Discord()
	
	
	public void connect() {
		
		
		api = Javacord.getApi(token, true);
		
		
		api.connect(new FutureCallback<DiscordAPI>() {

			
			public void onFailure(Throwable t) {
				
				t.getStackTrace();
				
			}//end onFailure

			
			public void onSuccess(DiscordAPI api) {

				
				api.getChannelById(channel).sendMessage("SUCCESS");
				
			}//end onSuccess

			
		});//end connect(FutureCallback)
		
	}//end connect()
	

	
	
	public void message(String msg ,String channel) {

		
		if(msg == null && channel ==null) {
			return;
		}
		
		api.getChannelById(channel).sendMessage(msg);

	}
	
	
	public void message(String msg, File file ,String channel) {

		
		if(msg == null && channel ==null) {
			return;
		}
		
		if(file != null) {
			if(!file.exists()) {
				//File not exists
				
				
			}else {
				api.getChannelById(channel).sendFile(file);
			}//if file.exists
			
		}//if file not null

		

		api.getChannelById(channel).sendMessage(msg);

		file = null;
	}
	
}
`

DEBUG
07:52:00.824 [pool-2-thread-1] DEBUG de.btobastian.javacord.ImplDiscordAPI - Checking token ************************************************************awE
07:52:00.827 [pool-3-thread-1] DEBUG de.btobastian.javacord.ImplDiscordAPI - Checking token ************************************************************awE
07:52:01.332 [pool-3-thread-1] DEBUG de.btobastian.javacord.ImplDiscordAPI - Checked token ************************************************************awE (valid: false)
07:52:01.332 [pool-2-thread-1] DEBUG de.btobastian.javacord.ImplDiscordAPI - Checked token ************************************************************awE (valid: true)
07:52:01.333 [pool-2-thread-1] DEBUG de.btobastian.javacord.ImplDiscordAPI - Requesting gateway (token: ************************************************************awE)
07:52:01.343 [pool-2-thread-1] DEBUG de.btobastian.javacord.ImplDiscordAPI - Requested gateway wss://gateway.discord.gg (token: ************************************************************awE)
07:52:01.943 [ReadingThread] DEBUG de.btobastian.javacord.utils.DiscordWebsocketAdapter - Sending identify packet
07:52:01.945 [ReadingThread] DEBUG de.btobastian.javacord.utils.DiscordWebsocketAdapter - Received HELLO packet
07:52:02.169 [Timer-0] DEBUG de.btobastian.javacord.utils.DiscordWebsocketAdapter - Sent heartbeat (interval: 41250)
07:52:02.170 [ReadingThread] DEBUG de.btobastian.javacord.utils.DiscordWebsocketAdapter - Received READY packet
07:52:06.172 [pool-2-thread-2] DEBUG de.btobastian.javacord.entities.impl.ImplChannel - Trying to send message in channel korea100 (id: 336438218490642442) (content: "SUCCESS", tts: false)
07:52:06.440 [pool-2-thread-2] DEBUG de.btobastian.javacord.entities.impl.ImplChannel - Sent message in channel korea100 (id: 336438218490642442) (content: "SUCCESS", tts: false)
07:52:43.418 [Timer-0] DEBUG de.btobastian.javacord.utils.DiscordWebsocketAdapter - Sent heartbeat (interval: 41250)
07:53:24.669 [Timer-0] DEBUG de.btobastian.javacord.utils.DiscordWebsocketAdapter - Sent heartbeat (interval: 41250)
07:54:05.918 [Timer-0] DEBUG de.btobastian.javacord.utils.DiscordWebsocketAdapter - Sent heartbeat (interval: 41250)

**Comment by BtoBastian** [comment]
Hmm, having multiple bots should normaly not cause any trouble even though I never tested it.
Can you please try adding a few seconds delay between the creation of the bots and also check if the ServerJoinListener is getting called?

**Comment by BtoBastian** [comment]
No answer since august
