### ISSUE TITLE
[Request] onServerLogon

### ISSUE THREAD

**Issue by xlash123** [BtoBastian/Javacord#61]
There is an onServerJoin method for determining when the bot is newly added to a server, but how about a listener that detects when the bot logs back onto a server it's already a member of. I can think of doing this by constantly looking at the ConcurrentHashMap of servers and detecting when it changes, but that seems like way too much computation.

**Comment by GamingAndStuffs** [comment]
Please elaborate a little bit. What do you mean by "when the bot logs back onto a server it's already a member of"?

**Comment by Treescrub** [comment]
If you wanted to know when it logs back on (going online I assume), it would be when the bot connects.

**Comment by xlash123** [comment]
Is there a listener for that? Basically what I'm trying to do is listen to every time the bot connects to a server (not necessarily the first time) and make or load a config file for that specific server.

**Comment by Treescrub** [comment]
I don't believe there's any normal ways the bot will "reconnect" to a server besides having it restarted. So probably for every server that the bot is on, loop through and generate/load a config file for each.

**Comment by xlash123** [comment]
I'll probably have to settle for that. I'm just wondering if it's possible to implement this within Discord's API.

**Comment by GamingAndStuffs** [comment]
I don't understand what you would want to implement though. Just use @Treescrub 's solution in the Future you passed to DiscordAPI#connect(), and that should cover every time you go online in the servers the bot is already in, and just do the same in a ServerJoinListener for new servers.

**Comment by xlash123** [comment]
Oh. I see. Thanks.
