### ISSUE TITLE
Can't Be Executed

### ISSUE THREAD

**Issue by HunBurry** [BtoBastian/Javacord#67]
Followed the tutorials exactly, downloading all the files, setting up the packages, etc. Have two errors:

1: When trying to run the shaded.jar from command line, I get a no main manifest attribute error. 

![screenshot 3](https://user-images.githubusercontent.com/20629592/28992586-6c7ff4da-796e-11e7-8929-3ba7f59542fd.png)

2: When trying to run the "ping" example, using my token, I get a can't be executed error.

![eclipse_error](https://user-images.githubusercontent.com/20629592/28992589-72792a00-796e-11e7-84d8-adce4caad824.png)

Any help on either?

**Comment by HunBurry** [comment]
Please note - I fixed the class error after posting, didn't catch it until after I took the screenshot.

**Comment by that1guy232** [comment]
His problem is he does not know how to use maven and set up dependency correctly I tried to tell him and show him  all he did was argue that he had it right.
