### ISSUE TITLE
Couldn't handle packet of type CHANNEL_DELETE

### ISSUE THREAD

**Issue by MedicOP** [BtoBastian/Javacord#69]
I don't know if this affects anything, but I keep getting this warning message:

```java
WARNING: Couldn't handle packet of type CHANNEL_DELETE. Please contact the devel
oper! (packet: {"is_private":false,"permission_overwrites":[{"allow":269484048,"
deny":0,"id":"218839529073803264","type":"member"},{"allow":0,"deny":1048576,"id
":"341658166720856065","type":"role"}],"nsfw":false,"parent_id":null,"name":"Oll
e's Channel","guild_id":"341658166720856065","bitrate":64000,"position":8,"id":"
343444472178147328","user_limit":0,"type":"voice"})
java.lang.NullPointerException
        at de.btobastian.javacord.entities.impl.ImplServer.removeVoiceChannel(Im
plServer.java:1108)
        at de.btobastian.javacord.utils.handler.channel.ChannelDeleteHandler.han
dleServerVoiceChannel(ChannelDeleteHandler.java:102)
        at de.btobastian.javacord.utils.handler.channel.ChannelDeleteHandler.han
dle(ChannelDeleteHandler.java:64)
        at de.btobastian.javacord.utils.PacketHandler$1.run(PacketHandler.java:7
1)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Mysterypotatoguy** [comment]
You're not getting any other errors before this, right?

**Comment by MedicOP** [comment]
Nope

**Comment by BtoBastian** [comment]
Hmm, that's strange...
Do you get this error message regularly or was this the only time?

**Comment by BtoBastian** [comment]
Is the bot, which deletes the channels, the same not which throws the exception?

**Comment by MedicOP** [comment]
Yes, it is.

**Comment by ryleykimmel** [comment]
2.0.15 has started producing random warnings like this for me as well. Upon channel connect I get

```WARN de.btobastian.javacord.utils.PacketHandler - Couldn't handle packet of type GUILD_CREATE.```

Reverting back to 2.0.14 solves the issue. :)

**Comment by MedicOP** [comment]
It seems like calling VoiceChannel.delete() removes the channel from the cache. Then when a CHANNEL_DELETE packet is received, it tries to remove it again causing NPE because it's not in the cache anymore.

Could either remove the code in VoiceChannel.delete() that removes it from the cache and just rely on the packet listener instead, or just add a null check in ChannelDeleteHandler.handle

**Comment by that1guy232** [comment]
I easily recreated this in the newest version,  
  ` @Command(aliases = "!test")
    public String test(Channel channel){
      channel.delete();
        return null;
    }`

**Comment by BtoBastian** [comment]
@MedicOP
Yes, the most likely the issue.

@ryleykimmel
Can you please show me the full error message? It's an other packet, so these two issues aren't related.

**Comment by BtoBastian** [comment]
Fixed :)
