### ISSUE TITLE
No timeout/delay when reconnecting?

### ISSUE THREAD

**Issue by bilde2910** [BtoBastian/Javacord#75]
**Disclaimer:**

This occurred with Javacord 2.0.14 (latest version as of May 19), and I would try again on 2.0.15 if I could, but I am unable to replicate the exact circumstances that caused this to happen in either 2.0.14 or 2.0.15. I deeply apologize for being unable to do this and therefore submitting an issue for an older version. I am submitting this in the hopes that a fix can be made, but feel free to close it if you feel that it's an invalid issue for that reason. I can't find any changes in the commits following the affected build that would indicate a fix has been made. If it is fixed then you can of course close this issue, but due to the potential severity regarding rate limits, I've chosen to submit it anyway.

---

I got an email this morning from Discord saying that they had changed the token of my bot after it had "connected to Discord more than 1000 times within a short time period." I connected to my server box to read the Javacord output and realized that Javacord doesn't seem to have a timeout when reconnecting to Discord. The connection failed repeatedly with error code 4004 (Authentication failed.) because the token was wrong. I am not sure what caused this error to appear initially because by the time I saw the error appear, the root cause had disappeared and it wasn't logged to disk properly on my end, but it looks like Javacord got itself stuck in an infinite reconnection loop. As I was watching the log, several connection attempts were made per second, apparent from the output produced by Javacord (see below).

I propose that a timeout is added when attempting to reconnect. Perhaps it should be possible to specify the timeout/delay period manually through some method.

Short snippet from the log:

```
INFO: Could not resume session. Reconnecting now...
Aug 08, 2017 2:20:18 AM de.btobastian.javacord.utils.JavacordLogger info
INFO: Websocket closed with reason Authentication failed. and code 4004 by server!
Aug 08, 2017 2:20:18 AM de.btobastian.javacord.utils.JavacordLogger info
INFO: Could not resume session. Reconnecting now...
Aug 08, 2017 2:20:18 AM de.btobastian.javacord.utils.JavacordLogger info
INFO: Could not resume session. Reconnecting now...
Aug 08, 2017 2:20:18 AM de.btobastian.javacord.utils.JavacordLogger info
INFO: Websocket closed with reason Authentication failed. and code 4004 by server!
```

Please let me know if you need more details.

**Comment by BtoBastian** [comment]
Hey,
thank you for mentioning this issue. You are right, there aren't any differences (relevant to this problem) between version 2.0.14 and 2.0.15 so this is still valid. I'll add a limit of ~5 reconnect attempts within 5 minutes. This should be no issue, if everything is working as expected, but prevent infinite reconnect loops.

I'm sorry for inconvenience

**Comment by GamingAndStuffs** [comment]
Hi,
I was wondering if maybe there could be a way to set the amount reconnect attempts? Just saying now because the system is already being worked on. I remember needing something like this a while back, but I don't remember what exactly for.

**Comment by BtoBastian** [comment]
Done :)
