### ISSUE TITLE
Discord API Deprecation

### ISSUE THREAD

**Issue by TrumpSupporter** [BtoBastian/Javacord#76]
Discord API and Gateway versions 3, 4, and 5 are deprecated, and will be discontinued on October 16th.

There is Discord API and Gateway version 6. Have you considered updating the Discord API version on this library to 6?

**Comment by BtoBastian** [comment]
Javacord is already using gateway version 6:
https://github.com/BtoBastian/Javacord/blob/master/src/main/java/de/btobastian/javacord/utils/DiscordWebsocketAdapter.java#L102
