### ISSUE TITLE
Incorrect User Agent Format

### ISSUE THREAD

**Issue by b1naryth1ef** [BtoBastian/Javacord#80]
Javacord prefaces the user agent string with `Javacord DiscordBot` instead of just `DiscordBot` as required. See the [official documentation](https://discordapp.com/developers/docs/reference#user-agent) for more information.

**Comment by BtoBastian** [comment]
Hmm, I honestly don't know why I append the library name in front, I really thought I did it according to the documentation.
Sorry, I'll fix it as soon as possible.

**Comment by BtoBastian** [comment]
Fixed :)
