### ISSUE TITLE
No valid token provided AND missing email or password. Connecting not possible!

### ISSUE THREAD

**Issue by Arinerron** [BtoBastian/Javacord#84]
I am 100% sure I am using the right token (I copy and pasted, and followed the guide you wrote exactly). I am still getting this:

```
Exception in thread "main" java.lang.IllegalArgumentException: No valid token provided AND missing email or password. Connecting not possible!
	at de.btobastian.javacord.ImplDiscordAPI.connectBlocking(ImplDiscordAPI.java:154)
	at Main.<init>(Main.java:18)
	at Main.main(Main.java:11)
```

Tried with blocking and non-blocking. What should I do?

**Comment by GamingAndStuffs** [comment]
Can you put your code (sans the token of course) somewhere?

**Comment by GamingAndStuffs** [comment]
Email and password login is deprecated and should probably never be used.

**Comment by Arinerron** [comment]
Alright, thanks.

This is my token (well, the format of the token. I edited multiple of the characters so it's not valid):
```
iNZJx8I2AxFywYIOtE_6avNiHZOuipUA
```

**Comment by GamingAndStuffs** [comment]
Oh, I meant everything except the token. Sorry for the confusion.

**Comment by Treescrub** [comment]
If that's about the same length as the actual "token", it doesn't seem like that's the token.

**Comment by Arinerron** [comment]
np. Here's the code:

```
import com.google.common.util.concurrent.FutureCallback;
import de.btobastian.javacord.*;
import de.btobastian.javacord.entities.message.Message;
import de.btobastian.javacord.listener.message.MessageCreateListener;

/**
 * A simple ping-pong bot.
 */
public class Main {
    public static void main(String[] args) {
        new Main("tokenhere");
    }

    public Main(String token) {
        DiscordAPI api = Javacord.getApi(token, true);
        //api.connectBlocking();
        api.connect(new FutureCallback<DiscordAPI>() {
            @Override
            public void onSuccess(DiscordAPI api) {
                api.registerListener(new MessageCreateListener() {
                    @Override
                    public void onMessageCreate(DiscordAPI api, Message message) {
                        if (message.getContent().equalsIgnoreCase("ping")) {
                            message.reply("pong");
                        }
                    }
                });
            }

            @Override
            public void onFailure(Throwable t) {
                t.printStackTrace();
            }
        });
    }

}

```

**Comment by Arinerron** [comment]
@Treescrub I tried both the `Client Secret` and `Token`. I've been mainly testing with the token it shows in the guide for getting started.

**Comment by GamingAndStuffs** [comment]
@Treescrub the token he put is the correct length (iirc it should be 32 characters).

**Comment by Arinerron** [comment]
The other one, called `Token` is 59 chars. I've tried both, but to no avail :/

**Comment by Treescrub** [comment]
The tokens I have for my bots are 59 characters. Is this a selfbot?

**Comment by Arinerron** [comment]
Huh, I just tried using discord's REST API; set the `Authorization` header to my tokens, and they all return http 401. This might be discord's fault and not javacord.

**Comment by BtoBastian** [comment]
Bot Tokens must be prefixed with "Bot " in the authorization header, that might be the reason you are getting this error with direct REST-calls.

I would recommend you to test the token with an other library, to see if it's an issue with Discord or with Javacord.

**Comment by BtoBastian** [comment]
Please check, if this error still exists in version 2.0.17.

**Comment by BtoBastian** [comment]
No answer since 5th of september

**Comment by xjzhang2037** [comment]
Heyo, checking in from 2020. This seems to be an issue when MFA is enabled, as this is not an issue with a test account (that i didnt set account security for)
but for my main, the token is prefixed with mfa.____________

**Comment by Saladoc** [comment]
I'm assuming you're trying to log in with a user account rather than a bot account. That is a violation of the discord terms of service and no longer supported. The possibility to even attempt this will be dropped completely in a future release.
