### ISSUE TITLE
Couldn't handle packet of type GUILD_CREATE

### ISSUE THREAD

**Issue by DoXBr** [BtoBastian/Javacord#95]
I keep getting this error with just one of the discord servers the bot is in, it still works fine everywhere else. The code has not been changed in any way before the problem started. 

`Sep 25, 2017 8:35:59 PM de.btobastian.javacord.utils.JavacordLogger warn
WARNING: Couldn't handle packet of type GUILD_CREATE. Please contact the developer! (packet: {"default_message_notifications":0,"unavailable":false,"owner_id":"221202188200837120","roles":[{"color":0,"permissions":67111936,"managed":false,"name":"@everyone","mentionable":false,"position":0,"id":"300752710549110784","hoist":false},{"color":0,"permissions":104324160,"managed":false,"name":"Scourge","mentionable":false,"position":11,"id":"300753265367187456","hoist":true},{"color":0,"permissions":1073741824,"managed":false,"name":"emoji","mentionable":false,"position":4,"id":"300964768502644738","hoist":false},{"color":0,"permissions":104324160,"managed":false,"name":"ally","mentionable":false,"position":3,"id":"300964771589783552","hoist":true},{"color":0,"permissions":37215296,"managed":false,"name":"strike-bot","mentionable":false,"position":1,"id":"311738863070478347","hoist":true},{"color":0,"permissions":335552518,"managed":false,"name":"OP","mentionable":false,"position":13,"id":"318886661293342722","hoist":false},{"color":0,"permissions":104320064,"managed":false,"name":"minecraft","mentionable":false,"position":10,"id":"328382915123871754","hoist":true},{"color":0,"permissions":133692480,"managed":false,"name":"MC mod","mentionable":false,"position":7,"id":"328882946285240331","hoist":false},{"color":0,"permissions":67226624,"managed":false,"name":"profile-bot","mentionable":true,"position":2,"id":"332072090591035393","hoist":true},{"color":0,"permissions":67111944,"managed":false,"name":"admin","mentionable":false,"position":14,"id":"342910372539269130","hoist":false},{"color":0,"permissions":70769728,"managed":false,"name":"IT","mentionable":false,"position":5,"id":"348487805309157379","hoist":false},{"color":0,"permissions":67624000,"managed":false,"name":"other","mentionable":false,"position":6,"id":"348492288646971394","hoist":false},{"color":0,"permissions":67619904,"managed":false,"name":"babah","mentionable":true,"position":8,"id":"350611286247342081","hoist":true},{"color":0,"permissions":515136,"managed":false,"name":"bots","mentionable":false,"position":12,"id":"350638794933927937","hoist":true},{"color":0,"permissions":104320064,"managed":false,"name":"eve","mentionable":false,"position":9,"id":"361818653798170635","hoist":false}],"icon":"7c15e1efa12169083f1ac063d80edaaa","system_channel_id":null,"afk_timeout":300,"features":[],"presences":[{"game":{"name":"Nexus Clash","type":0},"user":{"id":"160891867880226816"},"status":"online"},{"game":null,"user":{"id":"188027195812216832"},"status":"online"},{"game":null,"user":{"id":"199285545648652289"},"status":"online"},{"game":null,"user":{"id":"221202188200837120"},"status":"idle"},{"game":{"name":"xorg","type":0},"user":{"id":"245740941648855042"},"status":"online"},{"game":null,"user":{"id":"280537626904231946"},"status":"online"},{"game":{"name":"EVE Online","type":0},"user":{"id":"281052811687493633"},"status":"online"},{"game":null,"user":{"id":"283767953072062482"},"status":"dnd"},{"game":{"name":"EVE Online","type":0},"user":{"id":"313960010252025857"},"status":"online"},{"game":null,"user":{"id":"332037664968671233"},"status":"online"},{"game":null,"user":{"id":"332394259833552897"},"status":"online"},{"game":null,"user":{"id":"336496946627739661"},"status":"online"},{"game":null,"user":{"id":"339117013207351299"},"status":"online"}],"afk_channel_id":null,"members":[{"nick":"Zombie Williums","joined_at":"2017-08-29T04:16:43.055730+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"274843157294743552","avatar":"789cdfd2a7bda7ec85780cb8b4770f23","username":"tofury","discriminator":"2082"}},{"nick":null,"joined_at":"2017-05-12T16:21:51.387652+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"312625370677379072","avatar":"71aae7edf7b46a9f5f258593c5c0b7b3","username":"Zombie Rolo Tony","discriminator":"8421"}},{"nick":null,"joined_at":"2017-05-29T19:39:44.148977+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"318835536083025930","avatar":null,"username":"Krakonus","discriminator":"6716"}},{"nick":"grapes","joined_at":"2017-06-11T23:55:06.836973+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"224994363376140288","avatar":"0fd0b5957506c855f930e856a91326e0","username":"howaboutGrap3s","discriminator":"2564"}},{"nick":"CaptainFowl","joined_at":"2017-06-02T01:25:21.715690+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"188027195812216832","avatar":"1065e0d5a426a095fc070258ee991177","username":"HK-50","discriminator":"9144"}},{"nick":"Elaine Summers","joined_at":"2017-05-05T13:15:06.640081+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"283197405170630663","avatar":"cba1194d824319dc1427afad92c5dd1e","username":"Lady Selancourte","discriminator":"0252"}},{"nick":null,"joined_at":"2017-06-10T02:15:33.113443+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"322921680265805834","avatar":null,"username":"omagar","discriminator":"2641"}},{"nick":"Grau","joined_at":"2017-09-09T18:38:26.039133+00:00","roles":["300753265367187456","328382915123871754"],"deaf":false,"mute":false,"user":{"id":"154518951261503488","avatar":"d07ceefd13b30293816299ad39737e19","username":"Billy Bones","discriminator":"8506"}},{"nick":null,"joined_at":"2017-06-11T06:59:56.663559+00:00","roles":["300753265367187456","328382915123871754","361818653798170635"],"deaf":false,"mute":false,"user":{"id":"283767953072062482","avatar":"a056f25f29bd9f2b832394f3c94dcff4","username":"DoX","discriminator":"0070"}},{"joined_at":"2017-09-07T21:13:07.863276+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"306870305526382592","avatar":null,"username":"BorneLegaCy","discriminator":"4623"}},{"nick":"Blake Foley","joined_at":"2017-05-01T01:39:05.397539+00:00","roles":["300753265367187456","328382915123871754","361818653798170635"],"deaf":false,"mute":false,"user":{"id":"281052811687493633","avatar":"0dbb6a888e0cdc5d63bdbd059cc8347a","username":"VragNaroda","discriminator":"7810"}},{"nick":null,"joined_at":"2017-05-26T06:52:55.075590+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"268487199316508674","avatar":"9053b654d10f29e9d79065cbd6bd48ed","username":"Zebe","discriminator":"8193"}},{"joined_at":"2017-06-30T04:37:39.989394+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"281541249046020096","avatar":null,"username":"Rango","discriminator":"0903"}},{"joined_at":"2017-08-01T14:34:27.977271+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"302090471453491200","avatar":null,"username":"thepoorman","discriminator":"4516"}},{"nick":"DirtyDuke (Feral Clowder)","joined_at":"2017-05-17T13:34:02.315505+00:00","roles":["300964771589783552"],"deaf":false,"mute":false,"user":{"id":"298454258917834753","avatar":"e4d267034ecba86c28aa9add1559e530","username":"DirtyDuke","discriminator":"4948"}},{"nick":"Rita","joined_at":"2017-04-09T22:03:53.915000+00:00","roles":["300753265367187456","350611286247342081","328382915123871754"],"deaf":false,"mute":false,"user":{"id":"221202188200837120","avatar":"88f8ace827c654993cd03e1b8a6bd42f","username":"stelar","discriminator":"8437"}},{"joined_at":"2017-09-21T02:00:50.713136+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"360243922422857728","avatar":null,"username":"Jerry","discriminator":"0135"}},{"nick":"rich c","joined_at":"2017-07-27T13:46:00.511464+00:00","roles":["300753265367187456","328382915123871754"],"deaf":false,"mute":false,"user":{"id":"339117013207351299","avatar":"db25b32a54ff9d6d67547673d6e8d3f6","username":"Richard Skull","discriminator":"5988"}},{"joined_at":"2017-04-16T09:31:27.744000+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"282871755029348362","avatar":"8be16824e485f4d0a9cfbdb79f244bdd","username":"Wark","discriminator":"6009"}},{"joined_at":"2017-08-15T10:37:11.011839+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"271364080588029973","avatar":"7ca36e3d4a2ddfe4ee3ae61e1db5e6e8","username":"dnf","discriminator":"1044"}},{"joined_at":"2017-07-20T11:33:53.745755+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"324583873117814794","avatar":null,"username":"Zeonitely","discriminator":"0329"}},{"nick":null,"joined_at":"2017-07-06T05:42:56.280728+00:00","roles":["350638794933927937"],"deaf":false,"mute":false,"user":{"bot":true,"id":"332394259833552897","avatar":"9b20d767c2f56aeda075fb203621e9d2","username":"Barhah9000","discriminator":"8988"}},{"nick":null,"joined_at":"2017-08-13T12:17:23.555246+00:00","roles":["300753265367187456","350611286247342081"],"deaf":false,"mute":false,"user":{"id":"346265688370839552","avatar":null,"username":"nadiydanial","discriminator":"4640"}},{"nick":"tovag","joined_at":"2017-09-18T02:43:20.534550+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"324196255809142795","avatar":null,"username":"ScottieofArabia","discriminator":"0252"}},{"joined_at":"2017-06-10T05:55:42.461688+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"322976032422625280","avatar":null,"username":"H0tSh0t","discriminator":"8272"}},{"nick":null,"joined_at":"2017-05-26T14:24:05.495268+00:00","roles":["300964771589783552"],"deaf":false,"mute":false,"user":{"id":"243475946357653504","avatar":"7627300daab778873ae4eb11a75e7790","username":"Assassin","discriminator":"3253"}},{"nick":null,"joined_at":"2017-05-10T05:38:02.674814+00:00","roles":[],"deaf":false,"mute":false,"user":{"bot":true,"id":"280537626904231946","avatar":"015ee530bae8ca3f4e43e6755408719b","username":"strike-bot","discriminator":"6645"}},{"joined_at":"2017-09-21T02:02:54.879141+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"360244233376104448","avatar":null,"username":"Lars31252","discriminator":"8075"}},{"nick":null,"joined_at":"2017-06-10T08:00:16.358315+00:00","roles":["300753265367187456","328882946285240331","328382915123871754","361818653798170635"],"deaf":false,"mute":false,"user":{"id":"300867550630248449","avatar":"545d87973176dd28991481a1106724ff","username":"EasyDinner","discriminator":"4830"}},{"joined_at":"2017-08-09T00:02:35.637704+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"205097363293863936","avatar":"1338bd4f37e22b70b6d59dbff4c46f27","username":"ShadownetZero","discriminator":"9456"}},{"joined_at":"2017-06-12T07:46:56.767259+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"323729724255895553","avatar":null,"username":"yeti","discriminator":"3278"}},{"nick":"Ted Cruz: Zodiac Killer","joined_at":"2017-04-24T23:43:24.912641+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"191957613980680192","avatar":"08b7d3d96f72a6d327cb08653ace4a3a","username":"Jasten","discriminator":"4905"}},{"joined_at":"2017-08-09T10:26:33.546965+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"344788510550786048","avatar":null,"username":"Bosch","discriminator":"9235"}},{"joined_at":"2017-06-28T16:27:09.175658+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"329657234659213323","avatar":null,"username":"Keyser Suze","discriminator":"7189"}},{"nick":"Kryan(OhDandyDay)","joined_at":"2017-07-30T16:23:32.715195+00:00","roles":["300753265367187456","328382915123871754"],"deaf":false,"mute":false,"user":{"id":"341103561758867457","avatar":"8f8fbddbe67925c22991cc69f5788a92","username":"Kryan","discriminator":"0129"}},{"nick":"ledicious (Feral Clowder / RRF)","joined_at":"2017-05-10T05:26:06.669327+00:00","roles":["300964771589783552"],"deaf":false,"mute":false,"user":{"id":"245740941648855042","avatar":"a94dccc910765bc74edccd90f85603a1","username":"ledicious","discriminator":"2770"}},{"joined_at":"2017-05-27T20:06:25.278647+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"168885420371738624","avatar":null,"username":"coznowski","discriminator":"2412"}},{"nick":null,"joined_at":"2017-07-05T08:14:34.429760+00:00","roles":["350638794933927937","361818653798170635"],"deaf":false,"mute":false,"user":{"bot":true,"id":"332037664968671233","avatar":"39e43229fb19fbbc4eb8dd9b0e1a87fb","username":"ElectricEye","discriminator":"3984"}},{"nick":null,"joined_at":"2017-05-24T05:03:17.741970+00:00","roles":["300964771589783552"],"deaf":false,"mute":false,"user":{"id":"287007461712330752","avatar":null,"username":"Zuma","discriminator":"8460"}},{"nick":null,"joined_at":"2017-09-17T17:54:47.761960+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"359033608771600393","avatar":null,"username":"Exreen","discriminator":"4880"}},{"nick":null,"joined_at":"2017-08-05T01:51:46.963318+00:00","roles":["300753265367187456","328382915123871754"],"deaf":false,"mute":false,"user":{"id":"340942388908523541","avatar":"1dc502c9626b1b804cdae78e5a09476d","username":"bellzub","discriminator":"4810"}},{"nick":"Danger Doug","joined_at":"2017-08-23T12:15:37.825971+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"336496946627739661","avatar":"d593216657e2a5d09879a6d0438e2ddb","username":"Talisyne","discriminator":"1607"}},{"joined_at":"2017-06-13T00:00:34.740217+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"274808743479345152","avatar":"0db27f4f3cc0633930cd2b9e73f5b6f2","username":"Shauna","discriminator":"5589"}},{"nick":"Xeyseir (Feral Clowder)","joined_at":"2017-05-02T00:23:21.026034+00:00","roles":["300964771589783552"],"deaf":false,"mute":false,"user":{"id":"160891867880226816","avatar":"4c0f313f373ca52bb01b87a9d1e45a3d","username":"xzre","discriminator":"1278"}},{"nick":null,"joined_at":"2017-06-16T15:46:26.038895+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"124532238908915712","avatar":null,"username":"Fireheart","discriminator":"6419"}},{"nick":null,"joined_at":"2017-08-02T05:12:54.107660+00:00","roles":["300753265367187456","328382915123871754"],"deaf":false,"mute":false,"user":{"id":"341813246111645696","avatar":"5c73bd154071473d90406c8735eb118b","username":"Animefan666","discriminator":"6025"}},{"joined_at":"2017-09-25T08:19:11.241262+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"336086097170006017","avatar":"138c56480439c476858ed8fb90612521","username":"Balor","discriminator":"7790"}},{"nick":"ZennyO","joined_at":"2017-04-18T16:13:31.963000+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"303925658793541642","avatar":null,"username":"0208887531","discriminator":"5050"}},{"nick":"HarmanBargar","joined_at":"2017-04-10T11:20:46.801000+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"300547194392543233","avatar":"58ff0cc42b5ef22a76bc835741880c05","username":"rifter","discriminator":"3640"}},{"joined_at":"2017-06-19T13:19:32.060368+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"322516578484617216","avatar":null,"username":"slim","discriminator":"2808"}},{"joined_at":"2017-08-08T15:47:48.381254+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"344506779285061633","avatar":"3d0d581b8e970aa4365ce11a1dd5aa2a","username":"sdcyeahyouknowme","discriminator":"0530"}},{"nick":"Baraga","joined_at":"2017-05-16T08:46:07.219790+00:00","roles":["300753265367187456","328382915123871754","361818653798170635"],"deaf":false,"mute":false,"user":{"id":"313960010252025857","avatar":"fe4a95587d87d77fe99dfc507b4fab18","username":"Johnny P. Baraga","discriminator":"2443"}},{"nick":null,"joined_at":"2017-05-09T15:14:54.592617+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"309420124006252556","avatar":"36441b5a29bbc684e345e2747143ae66","username":"Bone Snapper","discriminator":"4908"}},{"joined_at":"2017-07-27T20:13:36.454921+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"340225100458622976","avatar":null,"username":"gryndryno","discriminator":"9347"}},{"joined_at":"2017-09-02T01:57:11.608409+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"310316353519353858","avatar":null,"username":"dopeboy33","discriminator":"5164"}},{"joined_at":"2017-06-17T11:19:21.265263+00:00","roles":[],"deaf":false,"mute":false,"user":{"id":"325595197406838784","avatar":"1d9b063a3d32b2d3d493038d8669b408","username":"legionarie88","discriminator":"5385"}},{"nick":"penguinpyro","joined_at":"2017-08-19T23:04:43.466033+00:00","roles":["300753265367187456"],"deaf":false,"mute":false,"user":{"id":"231242641801478145","avatar":"e52e35933c7712d9aaa16a859d534d01","username":"Penguinpyromaniac","discriminator":"5984"}},{"nick":"Bree Kong","joined_at":"2017-04-10T00:04:32.805000+00:00","roles":["300753265367187456","342910372539269130","328382915123871754"],"deaf":false,"mute":false,"user":{"id":"199285545648652289","avatar":"d0a25f283c5ff7ff822b348d0e22d931","username":"drones_need","discriminator":"6916"}}],"voice_states":[],"id":"300752710549110784","member_count":58,"emojis":[{"managed":false,"roles":[],"name":"zombie","id":"300965233231396865","require_colons":true},{"managed":false,"roles":[],"name":"dualnature","id":"300965304169922560","require_colons":true},{"managed":false,"roles":[],"name":"survivor","id":"300965378576875521","require_colons":true},{"managed":false,"roles":[],"name":"pker","id":"300965450299342848","require_colons":true},{"managed":false,"roles":[],"name":"guillotine","id":"322998465871478784","require_colons":true},{"managed":false,"roles":[],"name":"creeper","id":"331715960987844610","require_colons":true},{"managed":false,"roles":[],"name":"llama","id":"331716619632115712","require_colons":true},{"managed":false,"roles":[],"name":"diamond","id":"331717078946021376","require_colons":true},{"managed":false,"roles":[],"name":"zombie","id":"331717112286674955","require_colons":true},{"managed":false,"roles":[],"name":"creeper2","id":"331717135548153869","require_colons":true},{"managed":false,"roles":[],"name":"coal","id":"331766301162733570","require_colons":true},{"managed":false,"roles":[],"name":"emerald","id":"331766301930291212","require_colons":true},{"managed":false,"roles":[],"name":"gold_ingot","id":"331766303012552704","require_colons":true},{"managed":false,"roles":[],"name":"golden_apple","id":"331766303536971792","require_colons":true},{"managed":false,"roles":[],"name":"iron_ingot","id":"331766304342278144","require_colons":true},{"managed":false,"roles":[],"name":"Raw_Beef","id":"331766304698793984","require_colons":true},{"managed":false,"roles":[],"name":"ghast","id":"331766545518690305","require_colons":true},{"managed":false,"roles":[],"name":"tnt","id":"332051555920642062","require_colons":true},{"managed":false,"roles":[],"name":"chicken","id":"334294166236561428","require_colons":true},{"managed":false,"roles":[],"name":"potato","id":"335424938829938691","require_colons":true},{"managed":false,"roles":[],"name":"flakjacket","id":"345050258062966784","require_colons":true},{"managed":false,"roles":[],"name":"babah","id":"350414389918040065","require_colons":true},{"managed":false,"roles":[],"name":"babahspy","id":"350607510446800897","require_colons":true}],"large":false,"application_id":null,"joined_at":"2017-07-06T05:42:56.280728+00:00","verification_level":1,"explicit_content_filter":0,"channels":[{"permission_overwrites":[],"last_message_id":"359092425609969684","name":"welcome","topic":"Wanting to eat brainz? You're in the right place!","position":0,"id":"300752710549110784","type":0},{"permission_overwrites":[],"name":"General","bitrate":64000,"position":0,"id":"300752710549110785","user_limit":0,"type":2},{"permission_overwrites":[{"allow":0,"deny":805829713,"id":"300752710549110784","type":"role"},{"allow":515136,"deny":805314577,"id":"300753265367187456","type":"role"},{"allow":515136,"deny":805314577,"id":"350638794933927937","type":"role"},{"allow":523328,"deny":805306385,"id":"350611286247342081","type":"role"}],"last_message_id":"362016452896882700","last_pin_timestamp":"2017-09-23T00:26:09.989000+00:00","nsfw":false,"parent_id":"361453368876597259","name":"strike","topic":"Strike times: 0400 UTC | 1200 UTC","position":5,"id":"300752841851666434","type":0},{"permission_overwrites":[{"allow":0,"deny":805829713,"id":"300752710549110784","type":"role"},{"allow":515136,"deny":805314577,"id":"300753265367187456","type":"role"},{"allow":515136,"deny":805314577,"id":"350638794933927937","type":"role"},{"allow":121856,"deny":805707857,"id":"332072090591035393","type":"role"}],"last_message_id":"362017325169377280","last_pin_timestamp":"2017-08-25T23:35:22.181000+00:00","nsfw":false,"parent_id":null,"name":"general","topic":"Chatter about anything! (Plus details on strikes)","position":1,"id":"300752899024224256","type":0},{"permission_overwrites":[{"allow":0,"deny":805829713,"id":"300752710549110784","type":"role"},{"allow":515136,"deny":805314577,"id":"300753265367187456","type":"role"},{"allow":515136,"deny":805314577,"id":"311738863070478347","type":"role"},{"allow":515136,"deny":805314577,"id":"300964771589783552","type":"role"}],"last_message_id":"352207741194076170","nsfw":false,"parent_id":null,"name":"allies","topic":"For all those not Scourge Members to chat to the Scourge","position":3,"id":"304220820492910592","type":0},{"permission_overwrites":[{"allow":0,"deny":1024,"id":"300752710549110784","type":"role"},{"allow":1024,"deny":0,"id":"300753265367187456","type":"role"}],"last_message_id":"344583879342030858","nsfw":false,"parent_id":"361453368876597259","name":"availability","topic":null,"position":6,"id":"325861567373508608","type":0},{"permission_overwrites":[{"allow":0,"deny":1024,"id":"300752710549110784","type":"role"},{"allow":1024,"deny":0,"id":"300753265367187456","type":"role"},{"allow":515136,"deny":805314577,"id":"348492288646971394","type":"role"}],"last_message_id":"361793442726150145","last_pin_timestamp":null,"nsfw":false,"parent_id":"361454113499906048","name":"other_games","topic":"Got a game we should play? Tell us about it :)","position":8,"id":"326722815942459393","type":0},{"permission_overwrites":[{"allow":0,"deny":805829713,"id":"300752710549110784","type":"role"},{"allow":252928,"deny":805576785,"id":"332072090591035393","type":"role"},{"allow":511040,"deny":1,"id":"328382915123871754","type":"role"},{"allow":523328,"deny":805306385,"id":"328882946285240331","type":"role"},{"allow":515136,"deny":805314577,"id":"350638794933927937","type":"role"}],"last_message_id":"361487672319016981","last_pin_timestamp":"2017-09-18T12:37:03.177010+00:00","nsfw":false,"parent_id":"361817023954550785","name":"minecraft","topic":null,"position":7,"id":"328382876158787586","type":0},{"permission_overwrites":[{"allow":0,"deny":871366673,"id":"300752710549110784","type":"role"},{"allow":49283072,"deny":822083601,"id":"300753265367187456","type":"role"},{"allow":49283072,"deny":822083601,"id":"328382915123871754","type":"role"}],"nsfw":false,"parent_id":"361817023954550785","name":"Minecraft voice","bitrate":30000,"position":1,"id":"328494554225573888","user_limit":0,"type":2},{"permission_overwrites":[{"allow":0,"deny":871366673,"id":"300752710549110784","type":"role"},{"allow":3145728,"deny":822083601,"id":"300753265367187456","type":"role"}],"nsfw":false,"parent_id":"361454113499906048","name":"game_room_2","bitrate":30000,"position":2,"id":"328494590233673739","user_limit":0,"type":2},{"permission_overwrites":[{"allow":0,"deny":1024,"id":"300752710549110784","type":"role"},{"allow":1024,"deny":0,"id":"300753265367187456","type":"role"},{"allow":515136,"deny":805314577,"id":"348492288646971394","type":"role"}],"last_message_id":"350376382754324480","last_pin_timestamp":"2017-07-06T14:45:29.117537+00:00","nsfw":false,"parent_id":"361453804413255681","name":"ts_it_help_desk","topic":null,"position":2,"id":"332300683535450113","type":0},{"permission_overwrites":[{"allow":0,"deny":1024,"id":"300752710549110784","type":"role"}],"nsfw":false,"parent_id":null,"name":"Urban Dead","position":0,"id":"361453368876597259","type":4},{"permission_overwrites":[{"allow":0,"deny":1024,"id":"300752710549110784","type":"role"}],"nsfw":false,"parent_id":null,"name":"Helpdesk","position":1,"id":"361453804413255681","type":4},{"permission_overwrites":[{"allow":0,"deny":1024,"id":"300752710549110784","type":"role"}],"nsfw":false,"parent_id":null,"name":"Other games","position":2,"id":"361454113499906048","type":4},{"permission_overwrites":[{"allow":0,"deny":1024,"id":"300752710549110784","type":"role"}],"nsfw":false,"parent_id":null,"name":"Games","position":3,"id":"361817023954550785","type":4},{"permission_overwrites":[{"allow":0,"deny":1024,"id":"300752710549110784","type":"role"},{"allow":523328,"deny":805306385,"id":"361818653798170635","type":"role"}],"last_message_id":"362006117766791168","nsfw":false,"parent_id":"361817023954550785","name":"eve","topic":null,"position":4,"id":"361817686147072000","type":0}],"name":"Scourge","mfa_level":0,"region":"eu-central","splash":null})
org.json.JSONException: JSONObject["parent_id"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:658)
	at de.btobastian.javacord.entities.impl.ImplChannel.<init>(ImplChannel.java:106)
	at de.btobastian.javacord.entities.impl.ImplServer.<init>(ImplServer.java:140)
	at de.btobastian.javacord.utils.handler.server.GuildCreateHandler.handle(GuildCreateHandler.java:59)
	at de.btobastian.javacord.utils.PacketHandler$1.run(PacketHandler.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by BtoBastian** [comment]
Hey,
the latest version should fix this bug.
Direct download: http://ci.ketrwu.de/job/Javacord/branch/master/27/
Maven:
```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```
```xml
<dependency>
    <groupId>de.btobastian</groupId>
    <artifactId>Javacord</artifactId>
    <version>e241b20</version>
</dependency>
```
