### ISSUE TITLE
[Request] Try to reconnect x times every y minutes

### ISSUE THREAD

**Issue by DoXBr** [BtoBastian/Javacord#96]
For what I can tell, the way it works now is that by default the bot will try to reconnect 5 times in the last 5 minutes and if no connection is made it stops trying. But could it be done so it keeps trying to reconnect till a connection is made? Lets say, it tries 5 times in 5 minutes, but then waits a few more minutes and retries 5 more times, till it connects?
I know I could just increase the values to achieve something like that, but wouldn't be the ideal solution. I had worked a workaround for that in 2.0.14, but wasn't a very elegant solution either!

**Comment by BtoBastian** [comment]
v3 has a new reconnect system, which should work fine even for longer disconnects.
