### ISSUE TITLE
No method to check if a channel is marked nsfw

### ISSUE THREAD

**Issue by Watersfall** [BtoBastian/Javacord#97]

**Comment by BtoBastian** [comment]
Hey,
is this issue for version 2.x or the rewrite (aka. 3.0.0)?

**Comment by shawishi** [comment]
Why bother with 2.x?

**Comment by xaanit** [comment]
Looking at both [2.0 Channel](https://github.com/BtoBastian/Javacord/blob/master/src/main/java/de/btobastian/javacord/entities/Channel.java) and [3.0 Channel](https://github.com/BtoBastian/Javacord/blob/v_3/src/main/java/de/btobastian/javacord/entities/channels/Channel.java), it looks like both are missing NSFW (unless I missed it in my search with Ctrl + F somehow).

**Comment by BtoBastian** [comment]
https://github.com/BtoBastian/Javacord/blob/v_3/src/main/java/de/btobastian/javacord/entities/channels/ServerTextChannel.java#L15-L20

**Comment by BoneyIsSpooky** [comment]
Vote to close as this question has been answered in full.
